services:
  - type: web
    name: byra-ai-backend
    env: python        
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false

